language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
#      compiler:
#         - gcc
#      addons:
#        apt:
#          packages:
#            - g++-multilib
#           - gcc-multilib
    - os: osx
      osx_image: xcode8.3 # already includes Command Line Tools

# Create the project files
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
       docker pull gocnak/sourcesdk_steamrt_image
       docker run -it -d --name build_sdk gocnak/sourcesdk_steamrt_image
       docker exec build_sdk git clone https://github.com/momentum-mod/game.git ~/
       docker exec build_sdk ~/game/mp/src/creategameprojects
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       cd src && ./creategameprojects
    fi

# Build the project
script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
       xcodebuild -quiet -project games.xcodeproj -arch i386 -xcconfig devtools/release.xcconfig -configuration Release 
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
       docker exec build_sdk make -f ~/game/mp/src/games.mak
    fi
