version: 2
jobs:

  build_linux:
    docker:
      - image: gocnak/sourcesdk_steamrt_image
      
    working_directory: ~/mom_build
    
    steps:
      - checkout
      
      - run:
          name: Create game project files
          command: |
            cd mp/src
            ./creategameprojects
            
      - run: 
          name: Building the game
          command: |
            cd ~/mom_build/mp/src
            make -f games.mak

      - run:
          name: Zipping up artifacts
          command: |
            cd ~/mom_build
            zip -r binaries_linux.zip ~/mom_build/mp/game/bin ~/mom_build/mp/game/momentum/bin
            
      - store_artifacts:
          path: ~/mom_build/binaries_linux.zip

workflows:
  version: 2
  build_game:
    jobs:
      - build_linux
