version: 2
jobs:
  build_linux:
    machine: true

    working_directory: ~/mom_build

    steps:
      - checkout
      
      - run:
          name: Installing build tools
          command: sudo apt-get install build-essential gcc-multilib g++-multilib

      - run:
          name: Create game project files
          command: |
            cd game/mp/src/
            ./creategameprojects
      
      - run:
          name: Building the game
          command: sudo make -f games.mak

      - store_artifacts:
          path: game/mp/game/bin
          destination: bin_linux

      - store_artifacts:
          path: game/mp/game/momentum/bin
          destination: game_bin_linux

  build_mac:
    macos:
      xcode: "7.0"

    working_directory: ~/mom_build

    steps:
      - checkout

        # Create the game project stuff
      - run:
          name: Create game project files
          command: |
            cd game/mp/src
            ./creategameprojects

        # Run the XCode build
      - run: 
          name: Building the game
          command: xcodebuild -project games.xcodeproj -arch i386 -xcconfig devtools/release.xcconfig

      - store_artifacts:
          path: game/mp/game/bin
          destination: bin_mac

      - store_artifacts:
          path: game/mp/game/momentum/bin
          destination: game_bin_mac

workflows:
  version: 2
  build_game:
    jobs:
      - build_mac
      - build_linux
