version: 2
jobs:

  build_linux:
    docker:
      - image: gocnak/sourcesdk_steamrt_image
      
    working_directory: ~/mom_build
    
    steps:
      - checkout
      
      - run:
          name: Create game project files
          command: |
            cd src
            ./creategameprojects
            
      - run: 
          name: Building the game
          command: |
            cd ~/mom_build/src
            make -f games.mak

workflows:
  version: 2
  build_game:
    jobs:
      - build_linux
